environment: prod

services:
  typicod_service:
    base_url: https://jsonplaceholder.typicode.com
    end_points:
      get: /posts
      post: /posts

  reqres_service:
    base_url: https://reqres.in
    end_points:
      get: /api/register
      put: /api/users/2
  
  weather_service:
    base_url: https://api.openweathermap.org
    end_points:
      get: /data/2.5/weather?q=London&appid=
      api_key: 8866055d448161f19287d5745216d000

  internal_error_service:
    base_url: https://httpbin.org
    end_points:
      get: /status/500
